services:
  nginx:
    image: nginx:alpine
    container_name: segiq_nginx
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    environment:
      - ACTIVE_ENV=${ACTIVE_ENV:-app_blue}
    depends_on:
      - app_blue
      - app_green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    labels:
      - "service.type=load-balancer"

  app_blue:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: segiq_app_blue
    environment:
      - COLOR=blue
      - UVICORN_WORKERS=3
      - UVICORN_LOOP=uvloop # Options: uvloop: Ultra-fast C-based implementation (2x faster),
                              #          asyncio: Python's default event loop, auto: Automatically choose the best available
                              #          auto: Automatically choose the best available
      - UVICORN_LIMIT_CONCURRENCY=7000
    restart: unless-stopped
    labels:
      - "deployment.color=blue"

  app_green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: segiq_app_green
    environment:
      - COLOR=green
      - UVICORN_WORKERS=3
      - UVICORN_LOOP=uvloop
      - UVICORN_LIMIT_CONCURRENCY=7000
    restart: unless-stopped
    labels:
      - "deployment.color=green"

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./monitoring/grafana/sigiq_dashboard.json:/var/lib/grafana/dashboards/sigiq_dashboard.json:ro