groups:
  - name: sigiq_alerts
    rules:
      # alert if active connections drop to 0 for >60s
      - alert: NoActiveWebSocketConnections
        expr: sum(websocket_active_connections) == 0
        for: 60s
        labels:
          severity: warning
        annotations:
          summary: "No active WebSocket connections for more than 60 seconds"