global:
  scrape_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'sigiq-blue'
    static_configs:
      - targets: ['app_blue:8000']
    metrics_path: '/metrics'

  - job_name: 'sigiq-green'
    static_configs:
      - targets: ['app_green:8000']
    metrics_path: '/metrics'