name: SigIQ WebSocket CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build and test
      run: |
        # Build Docker images
        docker compose -f docker/compose.yml build
        
        # Start services
        docker compose -f docker/compose.yml up -d
        
        # Wait for services to be ready
        sleep 10
        
        # Run pytest
        pytest tests/ -v
        
        # Execute monitor script for 20s (as required)
        timeout 5s bash scripts/monitor.sh || true

    - name: Collect logs
      if: always()
      run: |
        docker compose -f docker/compose.yml logs > docker-logs.txt

    - name: Archive logs and artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-and-artifacts
        path: |
          tests/load_test_report.html
          docker-logs.txt
        retention-days: 30

    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker/compose.yml down --remove-orphans